CREATE OR REPLACE DATABASE MOVIES_DB;

CREATE OR REPLACE SCHEMA MOVIES_DB.BRONZE;
CREATE OR REPLACE SCHEMA MOVIES_DB.SILVER;
CREATE OR REPLACE SCHEMA MOVIES_DB.GOLD;
CREATE OR REPLACE SCHEMA MOVIES_DB.ORCHESTRATION;