CREATE OR REPLACE SECRET MOVIES_DB.BRONZE.OMDB_API_KEY_SECRET
TYPE = GENERIC_STRING
SECRET_STRING = 'OMDB_API_KEY';

CREATE OR REPLACE NETWORK RULE MOVIES_DB.BRONZE.OMDB_NETWORK_RULE
MODE = EGRESS
TYPE = HOST_PORT
VALUE_LIST = ('www.omdbapi.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION OMDB_EXTERNAL_ACCESS_INTEGRATION
ALLOWED_NETWORK_RULES = (MOVIES_DB.BRONZE.OMDB_NETWORK_RULE)
ALLOWED_AUTHENTICATION_SECRETS = (MOVIES_DB.BRONZE.OMDB_API_KEY_SECRET)
ENABLED = TRUE;