CREATE OR REPLACE FILE FORMAT MOVIES_DB.BRONZE.CSV_REVENUE_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE STAGE MOVIES_DB.BRONZE.REVENUE_STAGE
    FILE_FORMAT = CSV_REVENUE_FORMAT;

CREATE OR REPLACE TABLE MOVIES_DB.BRONZE.REVENUE_PER_DAY
(
    ID STRING,
    DATE DATE,
    TITLE STRING,
    REVENUE NUMBER(18,0),
    THEATERS NUMBER(10,0),
    DISTRIBUTOR STRING,
    SOURCE_FILE STRING
);

CREATE OR REPLACE TABLE MOVIES_DB.BRONZE.OMDB_MOVIES (
    TITLE STRING,
    IMDB_ID STRING,
    RESPONSE VARIANT
);

