CREATE OR REPLACE TABLE MOVIES_DB.SILVER.REVENUE_PER_DAY_CLEAN
(
    ID STRING,
    REVENUE_DATE DATE,
    TITLE STRING,
    TITLE_JK STRING,
    REVENUE NUMBER(18,0),
    THEATERS NUMBER(10,0),
    DISTRIBUTOR STRING,
    SILVER_LOADED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE MOVIES_DB.SILVER.OMDB_MOVIES_CLEAN
(
    TITLE STRING,
    TITLE_JK STRING,
    RELEASE_YEAR STRING,
    RATED STRING,
    RELEASED_DATE DATE,
    RUNTIME STRING,
    GENRE STRING,
    DIRECTOR STRING,
    WRITER STRING,
    ACTORS STRING,
    PLOT STRING,
    LANGUAGE STRING,
    COUNTRY STRING,
    AWARDS STRING,
    POSTER_URL STRING,
    METASCORE NUMBER,
    IMDB_RATING NUMBER(3,1),
    IMDB_VOTES NUMBER,
    IMDB_ID STRING,
    TYPE STRING,
    DVD STRING,
    BOX_OFFICE_RAW STRING,
    BOX_OFFICE NUMBER,
    PRODUCTION STRING,
    WEBSITE STRING,
    API_RESPONSE STRING,
    SILVER_LOADED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE MOVIES_DB.SILVER.OMDB_MOVIE_RATINGS
(
    IMDB_ID STRING,
    TITLE STRING,
    RATING_SOURCE STRING,
    RATING_VALUE_RAW STRING,
    RATING_SCORE_100 NUMBER(5,2),
    SILVER_LOADED_AT TIMESTAMP
);