CREATE OR REPLACE TABLE MOVIES_DB.GOLD.DIM_MOVIE (
    MOVIE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    IMDB_ID STRING,
    TITLE STRING,
    DISTRIBUTOR STRING,
    RELEASE_YEAR STRING,
    RATED STRING,
    RELEASED_DATE DATE,
    RUNTIME STRING,
    GENRE STRING,
    DIRECTOR STRING,
    ACTORS STRING,
    LANGUAGE STRING,
    COUNTRY STRING,
    METASCORE NUMBER,
    IMDB_RATING NUMBER(3,1),
    IMDB_VOTES NUMBER,
    BOX_OFFICE NUMBER,
    GOLD_LOADED_AT TIMESTAMP,
    GOLD_UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE MOVIES_DB.GOLD.DIM_DATE (
    DATE_KEY NUMBER,
    FULL_DATE DATE,
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH NUMBER,
    MONTH_NAME STRING,
    DAY_OF_MONTH NUMBER,
    DAY_OF_WEEK NUMBER,
    DAY_NAME STRING,
    WEEK_OF_YEAR NUMBER
);

CREATE OR REPLACE TABLE MOVIES_DB.GOLD.FACT_DAILY_REVENUE (
    REVENUE_ID STRING,
    DATE_KEY NUMBER,
    MOVIE_KEY NUMBER,
    REVENUE NUMBER(18,0),
    THEATERS NUMBER(10,0),
    GOLD_LOADED_AT TIMESTAMP
);