
CREATE OR REPLACE TASK MOVIES_DB.ORCHESTRATION.TASK_LOAD_REVENUE
WAREHOUSE = COMPUTE_WH
--SCHEDULE = 'USING CRON 0 0 1 1 * Europe/Warsaw'
AS
CALL MOVIES_DB.BRONZE.SP_LOAD_REVENUE_PER_DAY();

CREATE OR REPLACE TASK MOVIES_DB.ORCHESTRATION.TASK_LOAD_OMDB_API
WAREHOUSE = COMPUTE_WH
AFTER MOVIES_DB.ORCHESTRATION.TASK_LOAD_REVENUE
AS
CALL MOVIES_DB.BRONZE.SP_LOAD_OMDB_MOVIES_FROM_API();

CREATE OR REPLACE TASK MOVIES_DB.ORCHESTRATION.TASK_BUILD_SILVER
WAREHOUSE = COMPUTE_WH
AFTER MOVIES_DB.ORCHESTRATION.TASK_LOAD_OMDB_API
AS
CALL MOVIES_DB.SILVER.SP_BUILD_SILVER();

CREATE OR REPLACE TASK MOVIES_DB.ORCHESTRATION.TASK_BUILD_GOLD
WAREHOUSE = COMPUTE_WH
AFTER MOVIES_DB.ORCHESTRATION.TASK_BUILD_SILVER
AS
CALL MOVIES_DB.GOLD.SP_BUILD_GOLD();


ALTER TASK MOVIES_DB.ORCHESTRATION.TASK_LOAD_REVENUE RESUME;
ALTER TASK MOVIES_DB.ORCHESTRATION.TASK_LOAD_OMDB_API RESUME;
ALTER TASK MOVIES_DB.ORCHESTRATION.TASK_BUILD_SILVER RESUME;
ALTER TASK MOVIES_DB.ORCHESTRATION.TASK_BUILD_GOLD RESUME;
